version: '3'
services:
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - 7432:7432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: Ivan
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: docker_test
      PGDATA: /var/lib/postgres/data/pgdate
    restart: always
